---
- name: Create operator group
  kubernetes.core.k8s:
    host:
    api_key:
    validate_certs: false
    state: present
    apply: true
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: ansible-automation-platform-operator
        namespace: aap
      spec:
        targetNamespaces: aap
