apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: aap.astros.com
  namespace: ansible-automation-platform
spec:
  replicas: 1
  authentication:
    sso:
      type: saml
      saml:
        metadataUrl: "https://login.microsoftonline.com/{tenant_id}/federationmetadata/2007-06/federationmetadata.xml"
        entityIssuer: "https://sts.windows.net/{tenant_id}/"
        ssoUrl: "https://login.microsoftonline.com/{tenant_id}/saml2"
      clientId: "<your_client_id>"
      clientSecret: "<your_client_secret>"
