apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: aap.astros.com
  namespace: ansible-automation-platform
spec:
  replicas: 1
  authentication:
    sso:
      type: saml
      saml:
        metadataUrl: "https://login.microsoftonline.com/${AZURE_TENANT_ID}/federationmetadata/2007-06/federationmetadata.xml"
        entityIssuer: "https://sts.windows.net/${AZURE_TENANT_ID}/"
        ssoUrl: "https://login.microsoftonline.com/${AZURE_TENANT_ID}/saml2"
      clientId: "${AZURE_CLIENT_ID}"
      clientSecret: "${AZURE_CLIENT_SECRET}"
