name: Deploy AAC with ArgoCD

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual triggering from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy with ArgoCD
        run: |
          kubectl apply -f roles/ansible-controller-sso/tasks/main.yml --namespace ansible-automation-platform
