name: "TruffleHog"
on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop
jobs:
  scan:
    runs-on: security
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        base: ""
        head: ${{github.ref_name}}
        extra_args: --only-verified
